version: '3.1'

services:
  backend:
    build: ./backend
    container_name: backend_compose
    ports:
      - 3201:3201
    environment:
      - PORT=3201
    volumes:
      - /app/node_modules
      - ./backend:/app
    
  frontend:
    build: ./frontend
    container_name: frontend_compose
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend
